### ISSUE TITLE
自定义添加搜索?

### ISSUE THREAD

**Issue by sxml** [tangxiadi/searchEngineJumpSU#1]
添加后 搜索结果页不显示跳转导航?

**Comment by tangxiadi** [comment]
因为各网站的元素不一致，无法用一个统一的方式提取搜索关键词和插入导航条。您可以自行在脚本里增加搜索引擎支持，脚本第一个google引擎示例有详细的说明，有简单的html和js基础即可修改

**Comment by tangxiadi** [comment]
<img width="730" alt="js" src="https://user-images.githubusercontent.com/9555093/235987817-6d1b856f-b9d6-4024-978c-3af1568f53c5.png">
