### ISSUE TITLE
脚本在google.com上失效

### ISSUE THREAD

**Issue by eric1932** [tangxiadi/searchEngineJumpSU#3]
![image](https://user-images.githubusercontent.com/10938293/48803625-0ffb0400-ecd8-11e8-88e9-faf87022f171.png)
如图

是不是因为Google修改了网页布局导致的

**Comment by ygjose** [comment]
Google改版后，又失效了！请问有没有办法再修复一下？

**Comment by ygjose** [comment]
更新一下脚本就好了，感谢@tangxiadi的付出！

**Comment by tangxiadi** [comment]
最新版本已修复
