### ISSUE TITLE
希望可以自行调整水平位置

### ISSUE THREAD

**Issue by Kennnnnnji** [tangxiadi/searchEngineJumpSU#5]
由于使用其他脚本导致的页面改变，如果能分网页调整位置就好了

**Comment by tangxiadi** [comment]
您可以在脚本里自行修改对应搜索引擎的css来调整位置，需要有简单的css编辑基础

**Comment by tangxiadi** [comment]
<img width="556" alt="css" src="https://user-images.githubusercontent.com/9555093/235987459-fb9b39e4-1b47-40c4-babf-d3ab9bc664f2.png">
